lobby:
     time: 60
     minimal-players: 8
     position:
          x: 0
          y: 4
          z: 0
          yaw: 0
          pitch: 0
          world: world
mysql:
     host: localhost
     port: 3306
     username: devathlon
     password: devathlon
     database: devathlon
     tableprefix: devathlon_