respawntime:
     STONE: 1
     IRON_ORE: 10
     COAL_ORE: 5
     DIAMOND_ORE: 30
     GOLD_ORE: 20
     LOG: 5
lobby:
     time: 60
     minimal-players: 8
     position:
          x: 0
          y: 4
          z: 0
          yaw: 0
          pitch: 0
          world: world
mysql:
     host: localhost
     port: 3306
     username: devathlon
     password: devathlon
     database: devathlon
     tableprefix: devathlon_