respawntime:
     STONE: 20
     IRON_ORE: 200
     COAL_ORE: 100
     DIAMOND_ORE: 600
     GOLD_ORE: 200
     LOG: 100
     COBWEB: 100
     LEAVES: 80
     LAPIS_ORE: 300
lobby:
     time: 60
     minimal-players: 8
     position:
          x: 0
          y: 4
          z: 0
          yaw: 0
          pitch: 0
          world: world
mysql:
     host: localhost
     port: 3306
     username: devathlon
     password: devathlon
     database: devathlon
     tableprefix: devathlon_